version: '2'
services:
  web:
    container_name: "dockerdev-nginx"
    image: nginx:1.13-alpine
    restart: always
    links:
     - fpm
    ports:
     - "8581:80"
    volumes:
     - ./docker-config/nginx/site.conf:/etc/nginx/conf.d/_site.conf:ro
    volumes_from:
     - fpm
  fpm:
    container_name: "dockerdev-fpm"
    image: angelxmoreno/php-fpm-alpine
    restart: always
    volumes:
     - .:/site
     - ./docker-config/fpm/ini/sessions.ini:/usr/local/etc/php/conf.d/redis_session.ini
    links:
     - mysql
     - redis
     - mongo
     - es
  mysql:
    container_name: "dockerdev-mysql"
    image: mariadb:10.1
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=dockerdev
     - MYSQL_USER=dockerdev
     - MYSQL_PASSWORD=dockerdev
     - MYSQL_DATABASE=dockerdev
    volumes:
     - ./data/mysql/:/var/lib/mysql
    ports:
     - "8582:3306"
  redis:
    container_name: "dockerdev-redis"
    image: redis:3.2-alpine
    restart: always
    ports:
     - "8583:6379"
    command: redis-server --appendonly yes --requirepass dockerdev
    volumes:
      - ./data/redis/:/data
  mongo:
    container_name: "dockerdev-mongo"
    image: mongo:3.0
    restart: always
    volumes:
     - ./data/mongo/:/data/db
    ports:
     - "8584:27017"
  es:
    container_name: "dockerdev-es"
    image: elasticsearch:2.4-alpine
    restart: always
    volumes:
     - ./data/es:/usr/share/elasticsearch/data
    ports:
     - "8585:9200"
     - "8586:9300"
